server:
  port: 9002
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka-headless-service:8761/eureka
    register-with-eureka: true  #待测试服务暂时不需要注册
    fetch-registry: true         #不拉取服务列表,直接通过url访问
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: /tmp/rsa/rsa.pub # 公钥地址
    priKeyPath: tmp/rsa/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 30
