server:
  port: 9002
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka.ingress.com:8761/eureka
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: G:\\tmp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: G:\\tmp\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 30
