server:
  port: 8763
spring:
  application:
    name: gateway-service
eureka:
  client:
    service-url:
      defaultZone: http://test.ingress.com/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: false  #当你获取host时，返回的不是主机名，而是ip
zuul:
  prefix: /api # 添加路由前缀
  retryable: true
  routes:
    item-service: /item/**  #商品微服务
  add-host-header: true #携带请求本身的head头信息
  sensitive-headers: #匹配禁止使用的头信息，这里设置为null，否则set-cookie无效
ribbon:
  ConnectTimeout: 4000 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms
