server:
  port: 9001
  servlet:
    path: /
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka.ingress.com/eureka
    register-with-eureka: false  #待测试服务暂时不需要注册
    fetch-registry: true          #拉取服务列表,访问其它服务
